# Generated by Django 2.2 on 2020-07-07 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200623_2213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pub_date']},
        ),
        migrations.DeleteModel(
            name='Meta',
        ),
    ]
